apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  labels:
    app: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - name: admin-service
        imagePullPolicy: Always
        image: omarkorbi/admin-service
        ports:
        - containerPort: 8013
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin-service
spec:
  ports:
  - port: 8013
    protocol: TCP
  selector:
    app: admin-service
  type: NodePort